---
title: "Strings and Factors"
author: "Tara"
date: "10/27/2021"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
library(httr)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.clour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

sclae_colour_discrete = scale_color_viridis_d()
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
library(rvest)
library(p8105.datasets)
```


## Strings and regex

```{r}
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec, "jeff")

str_replace(string_vec, "jeff", "Jeff")


string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "^i think")

str_detect(string_vec, "i think$")

```

`str_detect` could go with `filter`
`str_replace` could go with `mutate`
(can replace with nothing to get rid of it too)

Strings are case sensitive!

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "^i think")
str_detect(string_vec, "i think$")
```

Carrot refers to **begining of line**
Dollar sign is for **end of the line**

```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"[Bb]ush")
```

The brackets act like "or"

